version: "3"
services:
  web:
    image: simone84/centos6-tomcat8:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "8088:8080"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet1
networks:
  webnet:
  webnet1:
